export const mockProducts = [
  {
    id: '1',
    name: 'Professional Cordless Drill',
    category: 'Power-Tools',
    price: 129.99,
    stock: 15,
    rating: 4.8,
    image: '/cordless-drill.png',
    description: '20V MAX lithium-ion cordless drill with 2 batteries',
    inStock: true,
  },
  {
    id: '2',
    name: 'Heavy Duty Hammer',
    category: 'Hand-Tools',
    price: 34.99,
    stock: 42,
    rating: 4.9,
    image: '/construction-hammer.png',
    description: '16oz steel claw hammer with fiberglass handle',
    inStock: true,
  },
  {
    id: '3',
    name: 'Circular Saw',
    category: 'Power-Tools',
    price: 189.99,
    stock: 8,
    rating: 4.7,
    image: '/circular-saw.png',
    description: '7-1/4 inch circular saw with laser guide',
    inStock: true,
  },
  {
    id: '4',
    name: 'Screwdriver Set',
    category: 'Hand-Tools',
    price: 24.99,
    stock: 0,
    rating: 4.6,
    image: '/screwdriver-set.jpg',
    description: '12-piece precision screwdriver set with case',
    inStock: false,
  },
  {
    id: '5',
    name: 'Paint Roller Kit',
    category: 'Painting',
    price: 19.99,
    stock: 28,
    rating: 4.5,
    image: '/paint-roller.png',
    description: 'Professional paint roller with 3 refills',
    inStock: true,
  },
  {
    id: '6',
    name: 'Adjustable Wrench Set',
    category: 'Hand-Tools',
    price: 44.99,
    stock: 19,
    rating: 4.8,
    image: '/wrench-set.jpg',
    description: '3-piece adjustable wrench set (6, 8, 10 inch)',
    inStock: true,
  },
  {
    id: '7',
    name: 'Electric Sander',
    category: 'Power-Tools',
    price: 79.99,
    stock: 12,
    rating: 4.7,
    image: '/electric-sander.jpg',
    description: 'Random orbital sander with dust collection',
    inStock: true,
  },
  {
    id: '8',
    name: 'Paint Brush Set',
    category: 'Painting',
    price: 29.99,
    stock: 35,
    rating: 4.6,
    image: '/colorful-paintbrushes.png',
    description: 'Professional 10-piece paint brush set',
    inStock: true,
  },
];

// filtersConfig.js (or keep inline)
export const categoryOptions = [
  { label: "All Categories", value: "all" },
  { label: "Power Tools", value: "power-tools" },
  { label: "Hand Tools", value: "hand-tools" },
  { label: "Painting", value: "painting" },
];

export const priceOptions = [
  { label: "All Prices", value: "all" },
  { label: "Under $50", value: "under50" },
  { label: "$50 - $100", value: "50to100" },
  { label: "Over $100", value: "over100" },
];

export const stockOptions = [
  { label: "All Items", value: "all" },
  { label: "In Stock", value: "instock" },
  { label: "Out of Stock", value: "outofstock" },
];
