import { mockProducts } from "./mockProducts";

export const mockOrders = [
  {
    orderId: "HW123456789",
    customerName: "Ava Patel",
    productId: "1",
    status: "in_transit",
    estimatedDelivery: "Tomorrow, 2:00 PM - 6:00 PM",
    lastUpdate: "Today at 11:45 AM",
    quantity: 1,
    total: 129.99,
    address: "123 Maple St, San Jose, CA",
  },
  {
    orderId: "HW987654321",
    customerName: "Liam Johnson",
    productId: "3",
    status: "delivered",
    estimatedDelivery: "Yesterday, 3:15 PM",
    lastUpdate: "Yesterday at 3:20 PM",
    quantity: 1,
    total: 189.99,
    address: "45 Sunset Blvd, Los Angeles, CA",
  },
  {
    orderId: "HW555555555",
    customerName: "Emily Zhang",
    productId: "8",
    status: "out_for_delivery",
    estimatedDelivery: "Today, 4:00 PM - 8:00 PM",
    lastUpdate: "Today at 1:30 PM",
    quantity: 2,
    total: 59.98,
    address: "89 River Rd, Seattle, WA",
  },
  {
    orderId: "HW111222333",
    customerName: "Noah Williams",
    productId: "2",
    status: "processing",
    estimatedDelivery: "Expected by Friday",
    lastUpdate: "Today at 9:00 AM",
    quantity: 1,
    total: 34.99,
    address: "789 Ocean Ave, Miami, FL",
  },
  {
    orderId: "HW999888777",
    customerName: "Sophia Kim",
    productId: "6",
    status: "canceled",
    estimatedDelivery: "—",
    lastUpdate: "2 days ago",
    quantity: 1,
    total: 44.99,
    address: "234 Lakeview Dr, Chicago, IL",
  },
  {
    orderId: "HW222333444",
    customerName: "Oliver Brown",
    productId: "5",
    status: "delivered",
    estimatedDelivery: "Oct 13, 10:30 AM",
    lastUpdate: "Oct 13, 11:00 AM",
    quantity: 3,
    total: 59.97,
    address: "456 Elm St, Austin, TX",
  },
  {
    orderId: "HW666777888",
    customerName: "Isabella Rivera",
    productId: "4",
    status: "in_transit",
    estimatedDelivery: "Tomorrow, 12:00 PM - 4:00 PM",
    lastUpdate: "Today at 2:00 PM",
    quantity: 1,
    total: 24.99,
    address: "987 Cherry Ln, Denver, CO",
  },
];
